DROP SCHEMA IF EXISTS thirdparty CASCADE;
CREATE SCHEMA thirdparty;
GRANT USAGE ON SCHEMA thirdparty TO PUBLIC;
 -- just for gen_random_uuid(), so far
CREATE EXTENSION pgcrypto WITH SCHEMA thirdparty;

DROP SCHEMA IF EXISTS tests CASCADE;
CREATE SCHEMA tests;
GRANT ALL PRIVILEGES ON SCHEMA tests TO PUBLIC;
CREATE EXTENSION pgtap WITH SCHEMA tests;
